### PR TITLE
Improve logging in denom metadata update task

### LINKED ISSUE #341: Confusing Log: Task ended for DenomUpsertTask
image

I feel like we can make this more informative.  

- I think it's weird that it says the Task ended, but it never says the task started
- I don't think its clear what DenomUpsert means.  

I would like to have the following changes made.

1. Add INF log for `Updating Denom Metadata from {base.api}`
2. Change `Task ended for DenomUpsertTask` to `Denom Metadata Update Complete

### PR DESCRIPTION
**Pull request by pharr117**
Closes #341

### CODE REVIEW

**Review by danbryan — CHANGES_REQUESTED** [review]
almost perfect, can you update this to actually say which server it's using?

**Comment by pharr117** [comment]
The starting line is:

```go
config.Log.Info(fmt.Sprintf("Updating Denom Metadata from %s", apiHost))
```

showing the API host we are pulling from

**Comment by danbryan** [comment]
108 too?

**Comment by pharr117** [comment]
Oh yeah gotcha, I will add it to the error outputs on both error blocks

**Comment by pharr117** [comment]
I just added the host to the API error block, and added the word "database" for the database error block to make that more explicit

**Review by danbryan — APPROVED** [review]

**Pull request merged**
