### PR TITLE
Feat/osmosis v16 upgrade + part of concentrated liquidity

### PR DESCRIPTION
**Pull request by pharr117**
This feature update adds the following:

1. Osmosis V16 querying support by bumping the Lens version to a supported commit
2. Partial Concentrated Liquidity message support
    * MsgCreatePosition - treated as a Send
    * MsgWithdrawPosition - treated as a Receive
    * MsgCollectSpreadRewards - treated as a Receive

The following messages are not included in this PR since they do not exist on Testnet for proper indexer testing:
* MsgCreatePool
* MsgFungifyChargedPositions

This was tested on the following blocks in testnet (since v16 has not been released to mainnet yet):

- /osmosis.concentratedliquidity.v1beta1.MsgCreatePosition
    - 1541366
    - 1541415
    - 1541493
    - 1541520
- /osmosis.concentratedliquidity.v1beta1.MsgWithdrawPosition
    - 1542243
    - 1542253
    - 1542257
    - 1569713
- /osmosis.concentratedliquidity.v1beta1.MsgCollectSpreadRewards
    - 1581946
    - 1588342
    - 1588349
    - 1588353

### CODE REVIEW

**Review by danbryan — APPROVED** [review]

**Review by danbryan — APPROVED** [review]

**Comment by pharr117** [comment]
I added parsing for `/osmosis.concentratedliquidity.poolmodel.concentrated.v1beta1.MsgCreateConcentratedPool`. I was able to get Osmosis [Localnet](https://github.com/osmosis-labs/osmosis/tree/main/tests/localosmosis#localosmosis) running a v16.1.1 version of Osmosis, and then I executed this TX on the localnet to get its form. This allowed me to test this message type even though I cannot find an example (currently) on mainnet.

**Comment by pharr117** [comment]
New commit for MsgCollectIncentives parsing, tested on mainnet block 10533306.

It uses the well-formed event `total_collect_incentives` event which contains a `tokens_out` attribute containing the collected incentives.

**Comment by pharr117** [comment]
Latest commit adds support for AddToPosition. AddToPosition clears out incentives and rewards for the position before sending the coins to the position.

It does the following:

1. Gets the collected spread rewards as a receive
2. Gets the collected incentives as a receive
3. Gets the tokens added to the position as a send

Tested on the following blocks:

* 10518073, 10518298, 10518305, 10518313 - has no rewards receiving
* 10561867 - Has rewards receiving as well as adding to position

**Comment by danbryan** [comment]
@pharr117 can this be closed?

**Pull request merged**
